### ISSUE TITLE
MSG+ - Not presented w/ Login

### ISSUE THREAD

**Issue by feerlessleadr** [tonywagner/EPlusTV#94]
Hi - thanks for considering adding NHL.tv from my other issue. In the meantime, I was hoping to get MSG+ to work with this to add to Emby. 

I converted the docker run command to compose, and am running the container with the following compose file:

```
version: "3.3"
services:
  eplustv:
    ports:
      - 8430:8000
    volumes:
      - ./data:/app/config
    environment:
      - MSGPLUS
      - MSGPLUS_USER=msgplus@mydomain.com
      - MSGPLUS_PASS=YG*b&R7NZ*Dy9NbBJGw4cUVXWA #<-- Not my actual password, but it is similar as my password is set of random letters/numbers/symbols. Not sure if this is messing anything up
      - PUID=1000
      - PGID=1000
    image: m0ngr31/eplustv
```

When I run the container, I'm not being prompted to login to msg+, instead, I'm just getting a prompt to login to ESPN+:

```
eplustv-eplustv-1  | > eplustv@2.1.10 start
eplustv-eplustv-1  | > ts-node index.ts
eplustv-eplustv-1  | 
eplustv-eplustv-1  | === E+TV v2.1.10 starting ===
eplustv-eplustv-1  | === ESPN+ Auth ===
eplustv-eplustv-1  | Please open a browser window and go to: https://www.espn.com/watch/activate
eplustv-eplustv-1  | Enter code:  WNMXNV
```

Can you let me know what I'm doing wrong?

::EDIT:: 
Just tried using the following run command:

```
docker run -p 8430:8000 -v ./data:/app/config -e PUID=1000 -e PGID=1000 -e MSGPLUS -e MSGPLUS_USER=msgplus@mydomain.com -e MSGPLUS_PASS=YG*b&R7NZ*Dy9NbBJGw4cUVXWA m0ngr31/eplustv
```

Having the same issue:
```
> eplustv@2.1.10 start
> ts-node index.ts

=== E+TV v2.1.10 starting ===
=== ESPN+ Auth ===
Please open a browser window and go to: https://www.espn.com/watch/activate
Enter code:  MXMTKM

```

**Comment by m0ngr31** [comment]
If you're just wanting MSG+, you'll need to pass in `ESPNPLUS=false` as an environment variable

**Comment by feerlessleadr** [comment]
Thanks - that fixed that. Unfortunately I must be doing something else wrong, as I can get the channels to show up in emby, but there is no guide data, and no streams that I'm able to play from MSG+.  The only thing that I get are blank channels.

Here is the log from the container:

```
eplustv-eplustv-1  | > eplustv@2.1.10 start
eplustv-eplustv-1  | > ts-node index.ts
eplustv-eplustv-1  | 
eplustv-eplustv-1  | === E+TV v2.1.10 starting ===
eplustv-eplustv-1  | === Getting events ===
eplustv-eplustv-1  | === Done getting events ===
eplustv-eplustv-1  | === Building the schedule ===
eplustv-eplustv-1  | === Done building the schedule ===
eplustv-eplustv-1  | === Starting Server ===
eplustv-eplustv-1  | Server started on port 8000
eplustv-eplustv-1  | Could not get a playlist for channel #55. Please make sure there is an event scheduled and you have access to it.
eplustv-eplustv-1  | Channel #55 has been idle for more than 5 minutes. Removing playlist info.
```

I have the channels start at 55 as that's where my other channels stop (not related to this addon).

**Comment by m0ngr31** [comment]
Are you importing the xmltv route into Emby? It won't play anything if there aren't any event scheduled, so you'll have to make sure something is on first

**Comment by feerlessleadr** [comment]
Yep - here is how I have emby setup:

![image](https://github.com/m0ngr31/EPlusTV/assets/288895/8ee5ddd5-d42e-483f-84a1-3dc3fc0edd58)


Last night the Devils, Islanders, and Rangers were all playing, and there was no guide data, and no streams on any of the channels.

**Comment by m0ngr31** [comment]
Oh, looking at your docker compose, it should be:

```yaml
version: "3.3"
services:
  eplustv:
    ports:
      - 8430:8000
    volumes:
      - ./data:/app/config
    environment:
      - ESPNPLUS=false
      - MSGPLUS=true
      - MSGPLUS_USER=msgplus@mydomain.com
      - MSGPLUS_PASS=YG*b&R7NZ*Dy9NbBJGw4cUVXWA #<-- Not my actual password, but it is similar as my password is set of random letters/numbers/symbols. Not sure if this is messing anything up
      - PUID=1000
      - PGID=1000
    image: m0ngr31/eplustv
 ```
