### ISSUE TITLE
Jellyfin MLB.tv error playing stream at all or freezing after a minute

### ISSUE THREAD

**Issue by geebru** [tonywagner/EPlusTV#97]
## Description

I feel like I've tried just about all I can figure out - EPlusTV was working fabulously during Spring Training, but ever since we hit regular season it's been a major struggle:
* Most of the time, I can't even get my channel to load (I'm a single team subscriber) - this may be Jellyfin as I know LiveTV is kind of meh on it, but I had Pluto.tv working okay. The error I get most often is: `[20:58:24] [ERR] [10] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/c2fc30da-ac5d-7a61-0025-5d460044fa1a/live.m3u8.`
* If I do get lucky enough to get the stream to connect, it can play the game for 1-2 minutes and then hard freezes and won't resume. Most of the time, refreshing loops back to bullet 1 until I get lucky again, then 1-2 minutes of game, then frozen.
* I've tried EPTV through my VPN, not through my VPN, and through Threadfin as well (just trying any method) and I seem to hit the same issues no matter what.

I'm running this in Unraid and I'm not seeing any errors from EPlusTVs end, but I'm posting in hopes someone else had similar issues and resolved them, or perhaps there's some things I'm missing here.

My compose section with EPlusTV is currently:
```
  eplustv:
    image: m0ngr31/eplustv
    container_name: eplustv-vpn
    volumes:
      - /mnt/cache/appdata/eplustv-vpn:/app/config
    environment:
      - PORT=8001
      - ESPNPLUS=false
      - MLBTV=true
      - MLBTV_USER=***
      - MLBTV_PASS=***
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
```

This is admittedly through the VPN again but it was working fine during Spring Training games. Any ideas?
